[package]
name = "greptimedb-client-cpp-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
arrow = "40"
arrow-schema = "40"
backtrace = "0.3"
futures = "0.3.28"
futures-util = "0.3.28"
#greptime-proto = { git = "https://github.com/niebayes/greptime-proto.git", rev = "091ffd86f1472161551f612da7fde3bc133cfdf6" }
greptimedb-client = { git = "https://github.com/GreptimeTeam/greptimedb-client-rust.git", rev = "bc32362adf0df17a41a95bae4221d6d8f1775656" }
lazy_static = "1.4"
libc = "0.2"
prost = "0.12"
serde = "1.0"
serde_derive = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.10"
strum = { version = "0.25", features = ["derive"] }

tracing = "0.1"
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-futures = { version = "0.2", features = ["futures-03"] }
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
